"use client";

import { useState } from "react";
import { usePortfolioStore } from "@/stores/portfolio-store";
import { formatCurrency, formatPercent } from "@/lib/utils";
import { Copy, Check, Share2, Eye, EyeOff } from "lucide-react";
import toast from "react-hot-toast";

export default function SnapshotPage() {
  const { holdings, portfolios, activePortfolioId } = usePortfolioStore();
  const [anonymize, setAnonymize] = useState(true);
  const [copied, setCopied] = useState(false);

  const portfolio = portfolios.find((p) => p.id === activePortfolioId);

  const totalValue = holdings.reduce(
    (sum, h) => sum + (h.current_price || 0) * h.quantity,
    0
  );
  const totalCost = holdings.reduce(
    (sum, h) => sum + h.avg_price * h.quantity,
    0
  );
  const totalPnl = totalValue - totalCost;
  const totalPnlPct = totalCost > 0 ? (totalPnl / totalCost) * 100 : 0;

  // Generate shareable text
  const snapshotText = (() => {
    const lines: string[] = [];
    lines.push(`Portfolio Snapshot${portfolio?.name ? ` - ${portfolio.name}` : ""}`);
    lines.push(`Generated: ${new Date().toLocaleDateString()}`);
    lines.push("");
    lines.push(`Total Value: ${anonymize ? "****" : formatCurrency(totalValue)}`);
    lines.push(`Total P&L: ${totalPnlPct >= 0 ? "+" : ""}${totalPnlPct.toFixed(2)}%`);
    lines.push(`Holdings: ${holdings.length} stocks`);
    lines.push("");
    lines.push("Stock | Weight | P&L%");
    lines.push("-".repeat(35));

    const sorted = [...holdings]
      .filter((h) => h.current_price)
      .sort(
        (a, b) =>
          (b.current_price || 0) * b.quantity -
          (a.current_price || 0) * a.quantity
      );

    for (const h of sorted) {
      const val = (h.current_price || 0) * h.quantity;
      const weight = totalValue > 0 ? (val / totalValue) * 100 : 0;
      const pnl = h.current_price
        ? ((h.current_price - h.avg_price) / h.avg_price) * 100
        : 0;
      lines.push(
        `${h.stock_symbol} | ${weight.toFixed(1)}% | ${pnl >= 0 ? "+" : ""}${pnl.toFixed(2)}%`
      );
    }

    lines.push("");
    lines.push("Generated by FinanceTracker");
    return lines.join("\n");
  })();

  async function handleCopy() {
    await navigator.clipboard.writeText(snapshotText);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div>
        <div className="flex items-center gap-2">
          <h1 className="text-2xl font-bold tracking-tight">Portfolio Snapshot</h1>
          <Share2 className="h-5 w-5 text-[hsl(var(--muted-foreground))]" />
        </div>
        <p className="text-sm text-[hsl(var(--muted-foreground))]">
          Generate a shareable text snapshot of your portfolio
        </p>
      </div>

      {/* Controls */}
      <div className="flex items-center gap-4">
        <button
          onClick={() => setAnonymize(!anonymize)}
          className="inline-flex items-center gap-2 rounded-md border border-[hsl(var(--border))] px-3 py-2 text-sm hover:bg-[hsl(var(--accent))] transition-colors"
        >
          {anonymize ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
          {anonymize ? "Values Hidden" : "Values Visible"}
        </button>
      </div>

      {/* Preview */}
      <div className="rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))]">
        <div className="flex items-center justify-between border-b border-[hsl(var(--border))] px-4 py-2">
          <span className="text-sm font-medium text-[hsl(var(--muted-foreground))]">Preview</span>
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 rounded-md bg-[hsl(var(--primary))] px-3 py-1.5 text-xs font-medium text-[hsl(var(--primary-foreground))] hover:bg-[hsl(var(--primary))]/90 transition-colors"
          >
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
            {copied ? "Copied!" : "Copy to Clipboard"}
          </button>
        </div>
        <pre className="overflow-x-auto p-4 text-xs leading-relaxed font-mono text-[hsl(var(--muted-foreground))]">
          {snapshotText}
        </pre>
      </div>
    </div>
  );
}
