"""add currency to holdings

Revision ID: 9ec39aff1e92
Revises: b388e46e4f03
Create Date: 2026-02-05 17:41:29.089143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec39aff1e92'
down_revision: Union[str, None] = 'b388e46e4f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'currency')
    # ### end Alembic commands ###
